# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', redactor.fields.RedactorField(max_length=10000, verbose_name='Текст')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('image', models.ImageField(upload_to='news', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
