# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=news.models.path_and_rename, verbose_name='Изображение'),
        ),
    ]
