# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlidesMainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slide_photo', verbose_name='Изображение')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Изображение для сладера',
                'verbose_name_plural': 'Изображения для сладера',
            },
        ),
    ]
