# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidesmainpage',
            name='text_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='slidesmainpage',
            name='text_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Текст'),
        ),
    ]
