# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20160716_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidesmainpage',
            name='image',
            field=models.ImageField(help_text='Рекомендуемый размер 1642x810.', upload_to=gallery.models.path_and_rename, verbose_name='Изображение'),
        ),
    ]
