# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=40, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=40, null=True, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('description_ru', models.TextField(max_length=500, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(max_length=500, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='photo', verbose_name='Изображение')),
            ],
            options={
                'verbose_name_plural': 'Блюда',
                'verbose_name': 'Блюдо',
            },
        ),
        migrations.CreateModel(
            name='DishOnMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_text', models.TextField(max_length=120, verbose_name='Текст')),
                ('dish_text_ru', models.TextField(max_length=120, null=True, verbose_name='Текст')),
                ('dish_text_en', models.TextField(max_length=120, null=True, verbose_name='Текст')),
                ('dish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Dish', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name_plural': 'Блюда на главной',
                'verbose_name': 'Блюдо на главной',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=40, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=40, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Ингридиенты',
                'verbose_name': 'Ингридиент',
            },
        ),
        migrations.CreateModel(
            name='TypeDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=40, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=40, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Типы блюд',
                'verbose_name': 'Тип блюда',
            },
        ),
        migrations.CreateModel(
            name='TypeIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=40, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=40, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Типы ингридиентов',
                'verbose_name': 'Тип ингридиента',
            },
        ),
        migrations.AddField(
            model_name='ingredients',
            name='type_ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.TypeIngredients', verbose_name='Тип ингредиента'),
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.TypeDish', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(to='product.Ingredients', verbose_name='Ингредиенты'),
        ),
    ]
