# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=18, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name_en',
            field=models.CharField(max_length=18, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name_ru',
            field=models.CharField(max_length=18, null=True, verbose_name='Название'),
        ),
    ]
