# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20160602_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(help_text='Рекомендуемый размер 550x550.', upload_to=product.models.path_and_rename, verbose_name='Изображение'),
        ),
    ]
